spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiedang/springCloud.git        # 配置git仓库的地址
          search-paths: springCloud                              # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: xiedang                                      # git仓库的账号
          password: xie19940306                                  # git仓库的密码
var:
  temp:
   username : ls
