server:
  port: 8082
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiedang.login.model
spring:
  application:
    name: login
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    type: org.apache.commons.dbcp.BasicDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true